# Generated by Django 3.2.7 on 2021-09-19 17:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('immediate', models.BooleanField(default=True)),
                ('after_seconds', models.PositiveBigIntegerField(default=0)),
                ('notification_type', models.CharField(choices=[('TRANSACTIONAL', 'TRANSACTIONAL'), ('PROMOTIONAL', 'PROMOTIONAL')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('updated_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WEB_PUSH', 'WEB_PUSH'), ('PUSH', 'PUSH'), ('EMAIL', 'EMAIL')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('body', models.CharField(max_length=4096)),
                ('attributes', models.JSONField(default=dict)),
                ('is_templated', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='notification.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
