# Generated by Django 3.2.5 on 2021-07-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='Product description', help_text='Add product description', max_length=8192, null=True),
        ),
    ]
