# Generated by Django 3.2.5 on 2021-07-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='number_of_items',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
